kibis-is/web-extension

.github/workflows/lint_build_test.yml, src/extension/config/networks.ts
* Update lint, build and test workflow to "Pull Request Checks"
* Remove Algoscan blockexplorer
* Update Voi testnet algod and indexer
=> feat: remove algoscan

webpack/webpack.common.config.ts, webpack/webpack.config.ts
* Update webpack config to chunk node modules if the chunk exceeds 4 MB.
=> feat: update webpack config to chunk node modules

.github/workflows/release.yml, .releaserc, bin/update_manifest_version.sh, src/manifest.common.json
* Update `manifest.common.json` version to the correct extension version
* Fix `./bin.update_manifest.sh` script to correctly update the `manifest.common.json` file
* Move build and package scripts to execute when a release is to be published
=> fix: manifest version not being updated

.github/ISSUE_TEMPLATE/bug_report_template.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request_template.yml, .github/actions/install-yq/action.yml, .github/workflows/release.yml, .releaserc, bin/update_issue_templates.sh
* Update bug report template
* Add config to enable issue template chooser
* Add feature request template
* Add script to add new version to bug report issue template
* Add script to release workflow
=> docs: add issue template chooser

dapp/App.tsx, src/extension/config/networks.ts
Update genesis hash and references for voitest-v1 (voi testnet)
=> fix: voitest-v1 config

src/extension/components/CreatePasswordInput/CreatePasswordInput.tsx, src/extension/components/SettingsSelectItem/SettingsSelectItem.tsx, src/extension/components/SettingsSubHeading/SettingsSubHeading.tsx, src/extension/components/SettingsSwitchItem/SettingsSwitchItem.tsx, src/extension/components/Warning/Warning.tsx, src/extension/features/settings/thunks/setSettings.ts, src/extension/features/settings/utils/createDefaultSettings.ts, src/extension/features/settings/utils/getInitialState.ts, src/extension/pages/AdvancedSettingsPage/AdvancedSettingsPage.tsx, src/extension/pages/ChangePasswordPage/ChangePasswordPage.tsx, src/extension/pages/CreateNewAccountPage/CreateNewAccountPage.tsx, src/extension/pages/CreatePasswordPage/CreatePasswordPage.tsx, src/extension/pages/GeneralSettingsPage/GeneralSettingsPage.tsx, src/extension/selectors/useSelectNetworks.ts, src/extension/translations/en.ts, src/extension/types/IAdvancedSettings.ts, src/extension/utils/selectDefaultNetwork.ts
* Use TestNet as default network
* Add option in settings to change to MainNet
* Add confirm modal and warning when switching to MainNet
* Decrease text size and modify padding on:
* Change Password page
* Create Password page
* Add account page
* Setting items
=> feat: use testnet by default and add settings option to allow mainnet

src/extension/config/networks.ts, src/extension/features/settings/thunks/setSettings.ts, src/extension/features/settings/utils/createDefaultSettings.ts, src/extension/features/settings/utils/getInitialState.ts, src/extension/pages/GeneralSettingsPage/GeneralSettingsPage.tsx, src/extension/selectors/useSelectPreferredBlockExplorer.ts, src/extension/types/IGeneralSettings.ts
* Add Voi Observer block exploreer to Voi testnet network config
* Settings now stores the selected block explorer for all networks
=> feat: add voi testnet block explorer

.github/actions/create-env-file/action.yml, .github/actions/download-latest-release-asset/action.yml, .github/workflows/publish_to_chrome_web_store.yml, README.md, bin/get_latest_release_asset.sh, bin/publish_to_chrome.sh, bin/update_issue_templates.sh
* Add action to download latest assets from release
* Add workflow to get Chrome Web Store access token, upload & publish to the Chrome Web Store on release
* Update badges in `README.md`
=> build: automatically upload and publish to the chrome store

src/extension/apps/main/Root.tsx, src/extension/enums/AccountsThunkEnum.ts, src/extension/features/accounts/slice.ts, src/extension/features/accounts/thunks/index.ts, src/extension/features/accounts/thunks/startPollingForAccountsThunk.ts, src/extension/features/accounts/thunks/stopPollingForAccountsThunk.ts, src/extension/features/accounts/utils/algorandAccountInformationWithDelay.ts, src/extension/features/accounts/utils/index.ts, src/extension/features/accounts/utils/lookupAlgorandAccountTransactionsWithDelay.ts, src/extension/features/accounts/utils/refreshTransactions.ts, src/extension/features/accounts/utils/updateAccountInformation.ts, src/extension/features/accounts/utils/updateAccountTransactions.ts
- Gets new transactions when polling for account information
=> feat: polls for new transactions when also fetching updated account information

src/extension/components/NativeBalance/NativeBalance.tsx, src/extension/translations/en.ts
* Use the network config native currency code in the minimum balance toolltip
=> fix: use network config code in minimum balance tooltip

.github/workflows/publish_to_chrome_web_store.yml
* Remove unnecessary `install` job dependency in the publish to chrome workflow
=> ci: remove unused job dependency in the deploy workflow

src/common/utils/formatCurrencyUnit.ts, src/extension/components/SendAssetModal/SendAmountInput.tsx, src/extension/components/SendAssetModal/SendAssetModal.tsx, src/extension/components/SendAssetModal/SendAssetModalSummaryContent.tsx, src/extension/features/send-assets/slice.ts, src/extension/features/send-assets/thunks/submitTransactionThunk.ts, src/extension/features/send-assets/types/ISendAssetsState.ts, src/extension/features/send-assets/utils/getInitialState.ts, src/extension/selectors/index.ts, src/extension/selectors/useSelectSendingAssetAmountInStandardUnits.ts
* Send asset amount input allows for decimals
=> fix: send asset number input allows for decimals

.github/ISSUE_TEMPLATE/bug_report_template.yml, .github/ISSUE_TEMPLATE/feature_request_template.yml, bin/update_issue_templates.sh
* Remove pre-release versions from bug report issue template
* Only add release versions to the bug report issue template
* Add @agoralabs-bot as default assignee to feature request issue templates
=> ci: only update issue template with release versions

src/extension/components/SettingsSelectItem/SettingsSelectItem.tsx, src/extension/components/SettingsSelectItem/SettingsSelectItemOption.tsx, src/extension/components/SettingsSelectItem/index.ts, src/extension/config/networks.ts, src/extension/modals/AddAssetModal/AddAssetModalArc200AssetSummaryContent.tsx, src/extension/pages/AppearanceSettingsPage/AppearanceSettingsPage.tsx, src/extension/pages/GeneralSettingsPage/GeneralSettingsPage.tsx, src/extension/translations/en.ts
* Refactor settings select items to use `react-select`
* Remove AlgoExplorer from Algorand network configs
* Use thousand separated values to the tooltip to the total supply on the add ARC-200 asset summary
* Add Allo block explorer to the Algorand MainNet
=> feat: remove algoexplorer option from algorand

src/extension/services/BackgroundEventListener.ts
* Focus main app window when the extension button is pressed and the main app window is open
* Focus registration app window when the extension button is pressed and the registration app window is open
* Fix issue where registration issue opened duplicate registration windows if the registration app window was already open
=> feat: bring the extension window to the forefront when the extension button is pressed

src/extension/components/CreatePasswordInput/CreatePasswordInput.tsx, src/extension/components/PasswordInput/PasswordInput.tsx, src/extension/modals/AddAssetModal/AddAssetModal.tsx, src/extension/modals/ConfirmPasswordModal/ConfirmPasswordModal.tsx, src/extension/modals/SendAssetModal/SendAssetModal.tsx, src/extension/modals/SignBytesModal/SignBytesContentSkeleton.tsx, src/extension/modals/SignBytesModal/SignBytesModal.tsx, src/extension/modals/SignTxnsModal/SignTxnsModal.tsx, src/extension/pages/CreatePasswordPage/CreatePasswordPage.tsx, src/extension/selectors/index.ts, src/extension/selectors/useSelectRegistrationPassword.ts, src/extension/selectors/useSelectRegistrationScore.ts
* Add input focus and 'Enter' key submission to:
- create password page
- sending asset modal
- add asset modal
- confirm password modal
- sign bytes modal
- sign txns modal
=> feat: pressing the enter key submits forms

src/extension/components/SideBar/SideBar.tsx
* Comment out WalletConnect scanning button in the `SideBar` component
=> feat: remove the walletconnect scanning button from the sidebar

README.md, src/manifest.v2.json, src/manifest.v3.json
* Remove `downloads` permission from the `manifest.json`
* Remove mention of `downloads` permission from the `README.md`
=> refactor: remove unused downloads permission

README.md
* Update Firefox shields badge with new link
* Fix some formatting issues in `README.md`
=> docs: firefox add on link in readme

src/common/enums/Arc0027MessageReferenceEnum.ts
* Replace `arc0013` references with `arc0027`
=> fix: replace arc0013 references with correct arc0027

src/extension/services/BackgroundMessageHandler/BackgroundMessageHandler.ts, src/extension/utils/fetchSupportedNetworks/fetchSupportedNetworks.ts, src/extension/utils/fetchSupportedNetworks/index.ts, src/extension/utils/isNetworkSupported/index.ts, src/extension/utils/isNetworkSupported/isNetworkSupported.ts, src/external/services/ExternalMessageBroker/ExternalMessageBroker.ts
* Use settings to filter supported networks for requests
=> fix: use settings to filter supported networks

src/extension/components/SettingsSelectItem/SettingsSelectItem.tsx, src/extension/features/settings/thunks/saveSettingsToStorage.ts, src/extension/pages/AdvancedSettingsPage/AdvancedSettingsPage.tsx
* Allow mainnet toggle now correctly toggles on after confirming
=> fix: mainnet checked state correctly passed to settings update

src/extension/modals/AddAssetModal/AddAssetModalArc200AssetSummaryContent.tsx, src/extension/pages/AssetPage/AssetPage.tsx
* Correct references to copy application ID tooltip label
=> fix: correct references to copy application id tooltip label

src/extension/components/EnterMnemonicPhraseInput/EnterMnemonicPhraseInput.tsx, src/extension/components/EnterMnemonicPhraseInput/utils/index.ts, src/extension/components/EnterMnemonicPhraseInput/utils/isPhrasesEmpty.ts, src/extension/translations/en.ts
* Convert commas to whitespace
* Add reset button to remove all phrases
=> fix: allow for comma separated seed phrases

src/extension/pages/AssetPage/AssetPage.tsx, src/extension/translations/en.ts
Changed the label for "remove asset" - which may indicate an on-chain action - to "hide asset", which is more easily understandable to be a UI action.
The translation dictionary keys are left as "remove" - not sure if those need to change as well.
=> fix: change label for "remove asset" to "hide asset"

.github/actions/publish-to-chrome-web-store/action.yml, .github/actions/publish-to-firefox-add-ons/action.yml, .github/actions/publish-to-microsoft-edge-add-ons/action.yml, .github/actions/use-dependencies/action.yml, .github/workflows/publish.yml, .github/workflows/pull_request_checks.yml, .github/workflows/refresh_chrome_web_store_token.yml, .github/workflows/release.yml
* Update `actions/checkout` to version 4
* Update `actions/setup-node` to version 4
* Use explicit Node version of 20.9.0
=> ci: set explicit node version in ci/cd pipelines

src/extension/components/AccountItem/AccountItem.tsx, src/extension/components/AccountSelect/AccountSelect.tsx, src/extension/components/AddressInput/AddressInput.tsx, src/extension/components/AddressInput/hooks/useAddressInput.ts, src/extension/components/AddressInput/types/IUseAddressInputState.ts, src/extension/constants/Dimensions.ts, src/extension/modals/SendAssetModal/SendAssetModal.tsx, src/extension/translations/en.ts
* Add menu button to select known accounts to "to" address on send asset modal
=> feat: add select account button to the address input

src/extension/features/send-assets/thunks/submitTransactionThunk.ts, src/extension/modals/SendAssetModal/SendAmountInput.tsx
* Add on focus function to the send asset input that updates the value to use an empty string; removing the zero
=> feat: remove zero when focusing on the send asset input

.github/actions/use-dependencies/action.yml, dapp-example/components/App/App.tsx, src/extension/constants/ARC0026.ts, src/extension/constants/ARC0300.ts, src/extension/constants/index.ts, src/extension/utils/parseURIToARC0300Schema/parseARC0300AccountImportSchema.ts, src/extension/utils/parseURIToARC0300Schema/parseURIToARC0300Schema.test.ts, src/extension/utils/parseURIToARC0300Schema/parseURIToARC0300Schema.ts
* Update `actions/cache` to version 4
* Support the legacy ARC-0026 scheme: `algorand://`
* Support the new ARC-0300 scheme: `avm://`
=> feat: support arc-0026 (algorand) and arc-0300 (avm) schemes

src/extension/modals/EnableModal/EnableModal.tsx
* Automatically add the first account in the list when enabling a dApp
=> feat: automatically add the first account on the enable modal

src/extension/utils/verifyTransactionGroups/verifyTransactionGroups.test.tsx, src/extension/utils/verifyTransactionGroups/verifyTransactionGroups.ts
* Allow single transactions with a an assigned group ID
=> fix: allow single transactions with a group id

src/extension/components/SeedPhraseDisplay/SeedPhraseDisplay.tsx, src/extension/components/SeedPhraseDisplay/index.ts, src/extension/components/SeedPhraseDisplay/types/IProps.ts, src/extension/components/SeedPhraseDisplay/types/index.ts, src/extension/components/SeedPhraseDisplay/utils/createMaskedSeedPhrase/createMaskedSeedPhrase.ts, src/extension/components/SeedPhraseDisplay/utils/createMaskedSeedPhrase/index.ts, src/extension/constants/Dimensions.ts, src/extension/constants/Routes.ts, src/extension/pages/CreateNewAccountPage/CreateNewAccountPage.tsx, src/extension/pages/SecuritySettingsIndexPage/SecuritySettingsIndexPage.tsx, src/extension/pages/ViewSeedPhrasePage/ViewSeedPhrasePage.tsx, src/extension/pages/ViewSeedPhrasePage/index.ts, src/extension/routers/SecuritySettingsRouter/SecuritySettingsRouter.tsx, src/extension/services/PrivateKeyService/PrivateKeyService.ts, src/extension/translations/en.ts
* Move displaying seed phrase to separate component 
* Add security settings page to display a seed phrase for a selected account
=> feat: view seed phrase for accounts

src/extension/components/Warning/Warning.tsx, src/extension/components/Warning/types/IProps.ts, src/extension/components/Warning/types/index.ts, src/extension/features/add-asset/thunks/addStandardAssetThunk.ts, src/extension/features/send-assets/thunks/submitTransactionThunk.ts, src/extension/modals/AddAssetModal/AddAssetModal.tsx, src/extension/modals/AddAssetModal/AddAssetModalStandardAssetSummaryContent.tsx, src/extension/modals/AddAssetModal/hooks/useAddAssetStandardAssetSummaryContent/index.ts, src/extension/modals/AddAssetModal/hooks/useAddAssetStandardAssetSummaryContent/types/IOptions.ts, src/extension/modals/AddAssetModal/hooks/useAddAssetStandardAssetSummaryContent/types/IState.ts, src/extension/modals/AddAssetModal/hooks/useAddAssetStandardAssetSummaryContent/types/index.ts, src/extension/modals/AddAssetModal/hooks/useAddAssetStandardAssetSummaryContent/useAddAssetStandardAssetSummaryContent.ts, src/extension/modals/SendAssetModal/SendAssetModal.tsx, src/extension/modals/SendAssetModal/SendAssetModalSummaryContent.tsx, src/extension/modals/SendAssetModal/hooks/useSendAssetSummaryContent/index.ts, src/extension/modals/SendAssetModal/hooks/useSendAssetSummaryContent/types/IOptions.ts, src/extension/modals/SendAssetModal/hooks/useSendAssetSummaryContent/types/IState.ts, src/extension/modals/SendAssetModal/hooks/useSendAssetSummaryContent/types/index.ts, src/extension/modals/SendAssetModal/hooks/useSendAssetSummaryContent/useSendAssetSummaryContent.ts, src/extension/modals/SendAssetModal/types/SendAssetModalSummaryContentProps.ts, src/extension/modals/SendAssetModal/types/index.ts, src/extension/pages/NFTPage/NFTPage.tsx, src/extension/pages/NFTPage/hooks/useNFTPage/types/IUseNFTPageOptions.ts, src/extension/pages/NFTPage/hooks/useNFTPage/useNFTPage.ts, src/extension/translations/en.ts, src/extension/utils/doesAccountFallBelowMinimumBalanceRequirementForTransactions/doesAccountFallBelowMinimumBalanceRequirementForTransactions.ts, src/extension/utils/doesAccountFallBelowMinimumBalanceRequirementForTransactions/index.ts, src/extension/utils/doesAccountFallBelowMinimumBalanceRequirementForTransactions/types/IOptions.ts, src/extension/utils/doesAccountFallBelowMinimumBalanceRequirementForTransactions/types/index.ts
* Add function to calculate if a list of transactions will bring an account's balance below the minimum balance requirement
* Throw error if attempting to send an asset that would cause an account's balance to fall below the minimum balance requirement
* Show a warning if attempting to send an asset that would cause the account's balance to fall below the minimum balance requirement
=> feat: dont allow sending of assets if account is below the minimum balance

src/extension/features/send-assets/thunks/createUnsignedTransactionsThunk.ts, src/extension/utils/groupTransactions/groupTransactions.ts, src/extension/utils/verifyTransactionGroups/verifyTransactionGroups.test.tsx, src/extension/utils/verifyTransactionGroups/verifyTransactionGroups.ts, src/external/services/ExternalMessageBroker/ExternalMessageBroker.ts
* Add test to check for signing transactions greater than length 16
=> test: add test to check for signing transactions greater than length 16

src/extension/contracts/ARC0072Contract/ARC0072Contract.test.ts, src/extension/contracts/ARC0200Contract/ARC0200Contract.test.ts, src/extension/contracts/ARC0200Contract/ARC0200Contract.ts, src/extension/contracts/BaseContract/BaseContract.ts, src/extension/contracts/BaseContract/types/INewBaseContractOptions.ts, src/extension/types/IARC0200AssetInformation.ts, src/extension/utils/createUnsignedARC0200TransferTransactions/createUnsignedARC0200TransferTransactions.ts, src/extension/utils/fetchARC0072AssetInformationWithDelay/fetchARC0072AssetInformationWithDelay.ts, src/extension/utils/fetchARC0200AssetHoldingWithDelay/fetchARC0200AssetHoldingWithDelay.ts, src/extension/utils/fetchARC0200AssetInformationWithDelay/fetchARC0200AssetInformationWithDelay.ts, src/extension/utils/mapARC0200AssetFromARC0200AssetInformation/mapARC0200AssetFromARC200AssetInformation.ts
* Use `string` instead of `bigint` in `IARC0200AssetInformation`
* Use string for the application ID when initializing contract wrappers
=> fix: arc-0200 assets with large total supplyies correctly parse

src/extension/components/EnterMnemonicPhraseInput/EnterMnemonicPhraseInput.tsx, src/extension/pages/AddAccountTypePage/AccountTypeItem.tsx, src/extension/pages/AddAccountTypePage/types/IItemProps.ts, src/extension/pages/AddAccountTypePage/types/index.ts, src/extension/pages/CreateNewAccountPage/CreateNewAccountPage.tsx, src/extension/pages/CreatePasswordPage/CreatePasswordPage.tsx, src/extension/pages/GetStartedPage/GetStartedPage.tsx, src/extension/pages/ImportAccountViaSeedPhrasePage/ImportAccountViaSeedPhrasePage.tsx, src/extension/translations/en.ts
* Whole copy fits in the add account type button
* Increase padding on seed phrase inputs to fit a maximum BIP-39 word
=> fix: refactor seed phrase UI to fit maximum mnemonic word to input

src/extension/routers/AddAccountMainRouter/AddAccountMainRouter.tsx
* Add state to `AddAccountMainRouter`:
- Remove `IAddAccountCompleteResult
- Add `password`
- Add `privateKey`
- Add `name`
- Add explicit boolean for confirm password modal
* Save account when private key and password states are fulfilled
=> fix: able to create account when password lock enabled

src/extension/contracts/ARC0072Contract/ARC0072Contract.ts, src/extension/contracts/ARC0200Contract/ARC0200Contract.ts, src/extension/contracts/BaseContract/BaseContract.ts, src/extension/services/PrivateKeyService/PrivateKeyService.ts
* Add function to pad null value for address based box names
* Parse explicit box names when using ARC-0200/0072 box references
=> feat: rekeyed accounts unable to send arc-0200 assets

src/extension/services/QuestsService/QuestsService.ts
* Send asset quest amount threshold lowered to be greater than 0
=> feat: send asset quest amount threshold lowered to be greater than 0

src/extension/components/EditableAccountNameField/EditableAccountNameField.tsx, src/extension/components/EditableAccountNameField/types/IProps.ts, src/extension/components/EditableAccountNameField/types/index.ts, src/extension/components/GenericInput/GenericInput.tsx, src/extension/components/GenericInput/index.ts, src/extension/components/GenericInput/types/IProps.ts, src/extension/components/GenericInput/types/index.ts, src/extension/constants/Limits.ts, src/extension/features/accounts/thunks/saveNewWatchAccountThunk.ts, src/extension/pages/AddWatchAccountPage/AddWatchAccountPage.tsx, src/extension/pages/AddWatchAccountPage/enums/StepsEnum.ts, src/extension/pages/AddWatchAccountPage/enums/index.ts, src/extension/pages/CreateNewAccountPage/CreateNewAccountPage.tsx, src/extension/pages/CreateNewAccountPage/enums/StepsEnum.ts, src/extension/pages/CreateNewAccountPage/enums/index.ts, src/extension/pages/CreateNewAccountPage/index.ts, src/extension/pages/ImportAccountViaSeedPhrasePage/ImportAccountViaSeedPhrasePage.tsx, src/extension/pages/ImportAccountViaSeedPhrasePage/enums/StepsEnum.ts, src/extension/pages/ImportAccountViaSeedPhrasePage/enums/index.ts, src/extension/pages/ImportAccountViaSeedPhrasePage/index.ts, src/extension/routers/AddAccountMainRouter/AddAccountMainRouter.tsx, src/extension/translations/en.ts
* Fix issue where watch accounts were not correctly being encoded
* Add new generic input component with character limit
* Use new `GenericInput` component when creating/importing new accounts
* Use new `GenericInput` component when changing the account name
=> feat: add a 32 byte limit on account names

src/extension/components/SeedPhraseDisplay/SeedPhraseDisplay.tsx, src/extension/components/SeedPhraseDisplay/types/IProps.ts, src/extension/pages/CreateNewAccountPage/CreateNewAccountPage.tsx, src/extension/pages/ViewSeedPhrasePage/ViewSeedPhrasePage.tsx
* Update seed phrase styling
* Add numbers to seed phrase display
=> feat: add numbers to the seed phrases and update style

package.json, src/extension/models/Ed21559KeyPair/Ed21559KeyPair.ts, src/extension/services/PrivateKeyService/PrivateKeyService.test.ts, src/extension/services/PrivateKeyService/PrivateKeyService.ts, webpack/plugins/WebExtPlugin/WebExtPlugin.ts, yarn.lock
* Remove `ws` package resolution.
* Add version-less `IPrivateKey` items to be included in the upgrade.
* Add tests for `PrivateKeyService.upgrade()` function.
=> fix legacy versions of private keys correctly upgrade

src/extension/components/AccountAvatarWithBadges/AccountAvatarWithBadges.tsx, src/extension/components/NewPasswordInput/NewPasswordInput.tsx, src/extension/components/NewPasswordInput/types/IProps.ts, src/extension/components/SideBar/SideBar.tsx, src/extension/hooks/useNewPasswordInput/useNewPasswordInput.ts, src/extension/hooks/useNewPasswordInput/utils/calculateScore/calculateScore.ts, src/extension/hooks/useNewPasswordInput/utils/calculateScore/index.ts, src/extension/utils/isWatchAccount/isWatchAccount.ts
* Watch account checks give precedence when adding a watch account badge.
* Password score state is updated when changing the `NewPasswordInput` value
=> fix: update score state when entering password

src/extension/config/networks.ts
* Add Voi mainnet configuration
=> feat: add voi mainnet configuration

src/background.ts, src/extension/components/NetworkSelect/NetworkSelectModal.tsx, src/extension/components/NetworkSelect/utils/containsOnlyStableNetworks/containsOnlyStableNetworks.ts, src/extension/components/NetworkSelect/utils/containsOnlyStableNetworks/index.ts, src/extension/features/networks/thunks/addCustomNodeThunk.ts, src/extension/features/networks/thunks/fetchFromStorageThunk.ts, src/extension/features/networks/thunks/removeCustomNodeThunk.ts, src/extension/features/networks/thunks/updateTransactionParamsForSelectedNetworkThunk.ts, src/extension/features/settings/thunks/fetchFromStorageThunk.ts, src/extension/features/settings/thunks/saveToStorageThunk.ts, src/extension/features/settings/utils/getInitialState.ts, src/extension/pages/AdvancedSettingsPage/AdvancedSettingsPage.tsx, src/extension/services/BaseService/BaseService.ts, src/extension/services/BaseService/index.ts, src/extension/services/BaseService/types/INewOptions.ts, src/extension/services/BaseService/types/index.ts, src/extension/services/ClientMessageHandler/ClientMessageHandler.ts, src/extension/services/NetworksService/NetworksService.ts, src/extension/services/ProviderActionListener/ProviderActionListener.ts, src/extension/services/QuestsService/QuestsService.ts, src/extension/services/SettingsService/SettingsService.ts, src/extension/services/SettingsService/index.ts, src/extension/services/SettingsService/types/index.ts, src/extension/translations/en.ts, src/extension/types/settings/IAdvancedSettings.ts, src/extension/utils/selectDefaultNetwork/selectDefaultNetwork.ts, src/extension/utils/supportedNetworksFromSettings/supportedNetworksFromSettings.ts
* Set mainnet to default.
* Add testnet toggle to settings.
* Toggling off an alternative network option correctly switches the network to the default one.
* Add mainnet badge to network select modal if not all networks are mainnet.
=> feat: use mainnet as default

package.json, src/extension/hooks/useGenericInput/useGenericInput.ts, src/extension/modals/EditAccountModal/EditAccountModal.tsx
* Edit account name no longer displays the previous edited account name.
=> fix: edit account name updates the input with the intended account name

src/extension/components/ARC0300AccountImportModalContent/ARC0300AccountImportModalContent.tsx, src/extension/components/NFTsTab/NFTsTab.tsx, src/extension/modals/AddAssetsModal/AddAssetsForWatchAccountModal.tsx, src/extension/modals/AddAssetsModal/AddAssetsModal.tsx, src/extension/modals/SendAssetModal/SendAssetModal.tsx, src/extension/modals/SignMessageModal/SignMessageModal.tsx
=> refactor: remove quest tracking

src/extension/components/Select/Select.tsx, src/extension/components/Select/SelectOption.tsx, src/extension/config/networks.ts
* Empty option no longer overflows in selects.
* Add Voi MainNet block explorer.
=> feat: add voi mainnet block explorer

src/extension/features/accounts/thunks/updateAccountsThunk.ts, src/extension/modals/WhatsNewModal/WhatsNewModal.tsx
* Updating accounts no longer uses just the last account item when saving accounts.
=> fix: watch accounts no longer lose the watch badge

src/extension/modals/WhatsNewModal/WhatsNewModal.tsx
* Whats new modal features/fixes item lists span the full width
=> fix: whats new features/fixes item lists span the full width

.github/ISSUE_TEMPLATE/feature_request_template.yml, .github/workflows/publish.yml, .github/workflows/pull_request_checks.yml, .github/workflows/release.yml, CHANGELOG.md, README.md, package.json, scripts/get_latest_release_asset.sh, src/extension/constants/Links.ts, src/manifest.common.json
* Update new org references.
* Use new Kibisis user for release and publish workflows.
=> chore: update new org references

README.md
* Fix table of contents.
* Add demo application link.
* Tidy up `README.md`
=> docs: add demo application link

dapp-example/components/ConnectMenu/ConnectMenu.tsx, dapp-example/components/Root/Root.tsx, dapp-example/constants/Networks.ts, dapp-example/constants/index.ts, dapp-example/hooks/useAVMWebProviderConnector/useAVMWebProviderConnector.ts, dapp-example/hooks/useUseWalletConnector/useUseWalletConnector.ts, dapp-example/utils/createPaymentTransaction.ts, dapp-example/utils/getRandomAlgodClient.ts, src/extension/config/networks.ts
* Update the Voi testnet genesis hash.
* Clean up dapp example styles.
* Use one source of truth for genesis hash in dapp example.
=> fix: update voi testnet genesis hash

package.json, src/client/README.md, src/client/adapters/LegacyProviderAdapter/LegacyProviderAdapter.ts, src/client/adapters/LegacyProviderAdapter/index.ts, src/client/main.ts, src/client/types/IWindow.ts, src/client/types/index.ts, webpack/utils/createCommonConfig.ts, yarn.lock
* Add `@agoralabs-sh/algorand-provider` package.
* Reinstate the `algorand-provider` adapter on the client.
* Update client `README.md` with reasoning for continuing to support the deprecated `algorand-provider`.
=> fix: reinstate algorand provider support

src/common/enums/LegacyUseWalletMessageReferenceEnum.ts, src/common/enums/index.ts, src/middleware/main.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/LegacyUseWalletMessageBroker.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/index.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/messages/LegacyUseWalletRequestMessage.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/messages/LegacyUseWalletResponseMessage.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/messages/index.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/types/ILegacyDiscoverResult.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/types/ILegacyUseWalletRequestMessage.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/types/ILegacyUseWalletResponseMessage.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/types/IUseWalletNetworkConfiguration.ts, src/middleware/message-brokers/LegacyUseWalletMessageBroker/types/index.ts
* Reinstate use-wallet v2 message broker.
=> fix: reinstate support for use-wallet v2

.github/pull_request_template.md, .github/workflows/pull_request_checks.yml, .github/workflows/release.yml, pnpm-lock.yaml, src/docs/whats_new.md, src/provider/utils/queueProviderEvent/queueProviderEvent.ts
* Updates the main window focus when main app is open and action is called.
=> fix: updates the focus when main window is open and action is enacted
